- name: declare and access a variables at all levels
  hosts: all
  connection: local
  become: yes
  tasks:
    - name: demo on the loops
      ansible.builtin.debug:
        msg: hello world from loops {{ item }}
      loop:
        - loop1
        - loop2
    - name: demo on loop2
      ansible.builtin.debug:
        msg: fruit name is  {{item.name}} & quality is {{item.quality}}
      loop:
        - { name: apple, quality: A }
        - { name: banana, quality: B }


