- name: demon on conditions
  hosts: all
  connection: local
  become: yes
  tasks:
    - name: hello from condition
      ansible.builtin.debug:
        msg: hello condition
      when: chandra == "true"