---
#variable at play level
- name: Declare and access variable at play level
  hosts: all
  become: yes
  vars:
    name2: chandra
  tasks:
    - name: Declare and access variable at play level
      ansible.builtin.debug:
        msg: welcome to {{name2}}


#variable at task level
- name: Declare and access variable at task level
  hosts: all
  become: yes
  tasks:
    - name: Declare and access variable at play level
      ansible.builtin.debug:
        msg: welcome to {{name1}}
      vars:
        name1: yoyo

#variable at inventry file  level
- name: Declare and access variable at inv level
  hosts: all
  become: yes
  tasks:
    - name: Declare and access variable at inv level
      ansible.builtin.debug:
        msg: welcome to {{URL}}

#variable at another level
- name: declare and access variable at another file
  hosts: all
  become: yes
  vars_files:
    - chandra.yaml
  tasks:
    - name: declare and access variable at another file
      ansible.builtin.debug:
        msg: welcome to {{chandra}}