---
- name: register a variable and store
  hosts: all
  become: yes
  connection: local
  tasks:
    - name: register variable
      ansible.builtin.shell: uptime
      register: out
    - name: store out variable
      ansible.builtin.debug:
        msg: "{{out}}"